# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controleacademico', '0002_auto_20161004_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargaHoraria', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('alunos', models.ManyToManyField(to='controleacademico.Aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controleacademico.Professor')),
            ],
        ),
    ]
