# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controleacademico', '0004_auto_20161005_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='alunos',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='cargaHoraria',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='alunos',
            field=models.ManyToManyField(through='controleacademico.Boletim', to='controleacademico.Aluno'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='controleacademico.Professor'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
    ]
