# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controleacademico', '0005_auto_20161009_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('alunos', models.ManyToManyField(to='controleacademico.Aluno')),
            ],
        ),
        migrations.RemoveField(
            model_name='boletim',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='alunos',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='professor',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='cargaHoraria',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controleacademico.Disciplina'),
        ),
        migrations.AddField(
            model_name='boletim',
            name='turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='controleacademico.Turma'),
            preserve_default=False,
        ),
    ]
