# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleacademico', '0008_turma_semestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='semestre',
        ),
        migrations.AddField(
            model_name='boletim',
            name='semestre',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
