# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controleacademico', '0010_turma_anoletivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoLetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='turma',
            name='periodoLetivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='controleacademico.PeriodoLetivo'),
            preserve_default=False,
        ),
    ]
