# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleacademico', '0012_boletim_medianota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletim',
            name='mediaNota',
            field=models.FloatField(verbose_name='media'),
        ),
    ]
